django_student/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
# from . import settings  不建议通过python包方式导入，django加载变量和代码存在顺序，直接导入settings可能导致报错。
from django.conf import settings



urlpatterns = [
    path('admin/',admin.site.urls),
    # 127.0.0.1:8000/student/*
    path('student/',include('student.urls')),
    # path('student/add.html',student_views.add,name='add_student'),
    # path('student/update.html/',student_views.update,name='update_student'),
    # path('student/delete.html/',student_views.delete,name='delete_student'),

    path('login/', include('login.urls',namespace='login')),
    # from student import views
    # http://127.0.0.1:8000
    # path('',views.index)

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# static(客户端请求的url/media/，电脑本地file文件夹)

login/urls.py
from django.urls import path
from . import views




urlpatterns = [
    path('index/', views.index),
    path('register/', views.register),
    path('do_register/', views.do_register),
    path('register_check/',views.register_check),
    path('login/',views.login),
    path('do_login/',views.do_login),
    path('logout/',views.logout),
    path('verify_image/(\d+)/(\d+)/',views.verify_image,name='verify_image')
]
app_name = 'login_account'

student/urls.py
from django.urls import  path
from django.urls import path,include
from . import views

urlpatterns = [
    path('index/',views.index,name='index'),
    # path('add/',views.index,name='add'),
    path('add/',views.add,name='add'),
    path('do_add/',views.do_add,name='do_add'),
    # path('update/',views.index,name='update'),
    path('<int:id>/update/',views.update,name='update'),
    path('<int:id>/do_update/',views.do_update,name='do_update'),
    # path('delete/',views.index,name='delete'),
    path('<int:id>/delete/',views.delete,name='delete'),
    path('export_excel/',views.export_excel,name='export_excle'),
    path('select/',views.select,name = 'select'),
    path('api_index/',views.api_index,name='api_index')

]





# 大多数情况两种方式可互换
# 如果参数就一个，且与业务关系较大，适合动态url匹配方式.  bili.com/av/58888  后台匹配path(av/<av_id>) . 视图函数的参数获取到。
# 方式二：参数较多，适合query string ， url后? 传参。
# bili.com/news/?page_no=2&page_size=20 , path('news/') ,视图韩式中request.GET['page_no']

student/models.py
from django.db import models


# Create your models here.

class Student(models.Model):
    GENDER_CHOICES = (
        (0,'未选择'),
        (1,'男'),
        (2,'女'),
        (3,'保密'),
    )
    no = models.IntegerField(verbose_name='学号',unique=True)
    name = models.CharField(verbose_name='姓名',max_length=20)
    age = models.PositiveIntegerField(verbose_name='年龄')
    gender = models.SmallIntegerField(verbose_name='性别',choices=GENDER_CHOICES,default=0)
    phone = models.CharField(verbose_name='电话号码',null=True,blank=True,max_length=50)
    avatar = models.ImageField(verbose_name='头像',upload_to='image/avatar')
    join_time = models.DateTimeField(verbose_name='加入时间',auto_now_add=True)
    last_modified_time = models.DateTimeField(verbose_name='上次修改时间', auto_now=True)

    # 初中生，班级对学生一对多关系，外键。  大学生换教室 多对多
    # class_ = models.ForeignKey(to='student.Class',on_delete=models.SET_NULL)
    # classes = models.ManyToManyField(to='student.Class')
    def __str__(self):
        return self.name

    # choices属性，前台取值  stu.get_field_display  原理写法
    # @property
    # def get_gender_display(self):
    #     for index,item in enumerate(self.GENDER_CHOICES):
    #         if item[0] == self.gender:
    #             value = item[1]
    #     return value

class Class(models.Model):
    GRADE_CHOICES = (
        (1,'小学一年级'),
        (2,'小学二年级'),
        (3,'小学三年级'),
        (4,'小学四年级'),
        (5,'小学五年级'),
        (6,'小学六年级'),
        (7,'初中一年级'),
    )
    no = models.IntegerField(verbose_name='班级号', unique=True)
    name = models.CharField(verbose_name='班级名', max_length=20)
    grade = models.SmallIntegerField(verbose_name='年级',choices=GRADE_CHOICES)
    capacity = models.IntegerField('容纳人数')
    address = models.CharField(verbose_name='班级位置',max_length=100)
    students = models.ManyToManyField(to='student.Student')







# question.choice_set  这种由一查多的思维跟原始sql相反，反向查询
# django manytomany 报错 reversename clish，反向查询名字冲突。结论 只需在一张表中写多对多字段

# 创建数据库，字段长度事先定义，不能太短存不进去，不能太长浪费空间age年龄可以small int，一个字节，整数范围-127到127。如果正整数0-255
# sql：create table name()
#      age Integer unsigned
# )


# 字段类默认不允许不插入空数据。如果某个字段可选是否插入数据，设置null和blank为True
# phone = models.CharField(verbose_name='电话号码',null=True,blank=True)

#
#  gender = models.SmallIntegerField(verbose_name='性别',choices=GENDER_CHOICES,

student/views.py
from django.shortcuts import render,reverse
from math import ceil
from django.db.models import Max
from student import models
from .models import Student,Class  # from .models import *
# Create your views here.
import xlwt
from io import BytesIO
from django_student import settings
import os
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect,HttpResponse


def index(request):
    """获取学生列表"""
    # 计算分页索引
    page_no = int(request.GET.get('page_no',1))
    page_size = int(request.GET.get('page_size',3))
    start_index = (page_no - 1) * page_size
    end_index = page_no * page_size

    # todo 多条件过滤
    # name_like="明"  gender="女"
    # Student.object.filter().count()

    # 查询
    rows_amount = Student.objects.all().count()
    # print(rows_amount)
    # page_amount = (rows_amount-0.1) // page_size + 1    # 9条/每页3条  整除时导致总页数多算了1， 解决方法一  行数-0.1 再除； 方法二ceil返回大于等于整数
    page_amount = ceil(rows_amount / page_size)
    student_list = Student.objects.all().order_by('no')[start_index: end_index]
    page_amount_list = [i for  i in range(page_amount)]   # [0,1,2]

    if page_no > page_amount :
        page_no=page_amount
        # error_message = '请求页码数超过最大页码'
    # e = error_message
    context={
        "student_list":student_list,
        'page_amount_list':page_amount_list,
        'page_no':page_no,
        # 'error_message':e,
        'page_previous' : page_no -1 or 1 ,
        'page_nex' : page_no +1 ,
    }
    return render(request,'student/index.html',context)

def select(request):
    # 模糊查询
    if request.method == 'GET':
        return render(request,'student/select.html',context={})
    if request.method == 'POST':
        name = request.POST.get('name')
        gender = request.POST.get('gender')
        if gender == '未选择':
            gender = '0'
        elif gender == '男':
            gender = '1'
        elif gender  == '女':
            gender = '2'
        elif gender == '保密':
            gender = '3'
        if name!= '' and gender !='':
            student_list = Student.objects.filter(name__icontains= name,gender=gender)
        elif name == '' and gender != '':
            student_list = Student.objects.filter(gender=gender)
        elif name != '' and gender == '':
            student_list = Student.objects.filter(name__icontains=name)
        context = {
            'student_list':student_list,
        }
        return render(request,'student/select.html',context)





def add(request):
    max_no = Student.objects.aggregate(Max('no'))
    next_no = max_no['no__max'] + 1
    context = {
        'next_no':next_no,
    }
    return render(request,'student/add.html',context)

def do_add(request):
    assert request.method == 'POST'
    no = request.POST['no']
    name = request.POST['name']
    age = request.POST['age']
    gender = request.POST['gender']
    phone = request.POST['phone']
    avatar = request.FILES.get('avatar')

    # 存储图片
    # files = request.FILES  # 文件img存储字段，open打开
    # file = files['avatar']
    # _file_name = file.name
    # _upload_to = Student.avatar.field.upload_to
    # avatar = _avatar_db_path = os.path.join(_upload_to,_file_name)
    models.Student.objects.create(no=no,name=name,age=age,gender=gender,phone=phone,avatar=avatar)
    context = {}
    # if no < 0 or no > 10000:
    #     error_message = '输入非法，学号范围为1-9999'
    # if Student.objects.filter(no=no).exists():
    #     max_no = Student.objects.aggregate(Max('no'))['max__no']
    #     error_message = f'学号已存在，目前最大学号为{max_no},建议学号设置为{max_no+1}。'
    # if gender not in [i[0] for i in Student.GENDER_CHOICES]:
    #     error_message = '性别可选值不正确'
    # if  error_message :
    #     context = {
    #         'error_message': error_message
    #     }
    return render(request,'student/success.html',context)

def update(request,id):
    student= Student.objects.get(id=id)
    text = Student.objects.filter(id=student.id)
    context = {
        "students":student,
        'stu':text,
    }
    return render(request,'student/update.html',context=context)

def do_update(request,id):
    assert request.method == 'POST'
    no = request.POST['no']
    name = request.POST['name']
    age = request.POST['age']
    gender = request.POST['gender']
    phone = request.POST['phone']
    avatar = request.FILES.get('avatar')
    student = Student.objects.get(id=id)
    student.no = no
    student.name = name
    student.age = age
    student.gender = gender
    student.phone = phone
    student.avatar = avatar
    student.save()
    return render(request, 'student/do_update.html', context={})

def delete(request,id):
    student = Student.objects.filter(id=id).delete()
    return render(request, 'student/delete.html')


def export_excel(request):
    """导出所有学生信息到excel文件"""
    # 设置HTTPResponse的类型
    response = HttpResponse(content_type='application/vnd.ms-excel')
    # 定义表名字
    response['Content-Disposition'] = 'attachment;filename=student.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    sheet = wb.add_sheet('student-order')
    # 写入文件标题
    sheet.write(0,0,'学号')
    sheet.write(0,1,'姓名')
    sheet.write(0,2,'年龄')
    sheet.write(0,3,'性别')
    sheet.write(0,4,'电话号码')
    # sheet.write(0,6,'头像')
    sheet.write(0,5,'加入时间')
    # 写入数据
    data_row = 1
    for i in Student.objects.all():
        join_time = i.join_time.strftime('%Y-%m-%d')[:10]
        # print(join_time)
        sheet.write(data_row,5,join_time)
        sheet.write(data_row,0,i.no)
        sheet.write(data_row,1,i.name)
        sheet.write(data_row,2,i.age)
        sheet.write(data_row,3,i.gender)
        sheet.write(data_row,4,i.phone)
        data_row = data_row +1
    # 写到IO
    output = BytesIO()
    wb.save(output)
    # 重新定位到开始
    output.seek(0)
    response.write(output.getvalue())
    return response


def api_index(request):
    """

    :param request:
    :return:
    """
    pass


# def cloth_sale_line(request):
#     # 后端渲染。 缺点不适合做动态图
#     #获取数据。 请求其他接口读数据库
#     #拼前端表格所需变量



    # 数据库查询查询学生信息
    # 数据拼成二维数组（第一行为字段名，后面的数据行，（选做）合并前两行、填充背景色和修改字体字号）
    # save(data.after="media/download/student_info.xlsx")
    # redirect(to="域名/media/download/student_info.xlsx")















# SELECT * from student_student LIMIT 0,3;   -- 学生1到学生3（包含3）
# SELECT * from student_student LIMIT 1,3;    --学生2到4
# -- limit跟python中的列表切片很像但参数含义不一样。 limit  1,3  下标（从0开始计第一行)1, 3 表示向后取的行数
# SELECT * from student_student LIMIT 6,3;
# SELECT  count(id) as amount from student_student;  --计算总行数

# page_no 第几页  page_size  一页显示几条 page_amount 总数据个数
#   1                   10
#  SELECT * from student_student LIMIT 0,{page_size};
# 第1页  每页10条                             0   10
# 第2页                                      10   10
#                                            20   10
#                                           start_index =  {page_no-1}*page_size
# 总页数    总行除以每页数向上取整             page_amount//page_size+1

# student_list = Student.objects.all().order_by('no')[1: 3]
#           start_index =  {page_no-1}*page_size
#           end_index = page_no * page_size

templates/student/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加学生信息</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="https://kit.fontawesome.com/c269860567.js"></script>
    <style>
        div{
            text-align: center;
        }
    </style>
</head>
<body>
<form enctype="multipart/form-data" action="/student/do_add/" method="post" id="student_from" novalidate>
    {% csrf_token %}
    <h1 align="center">增加student</h1>
    <p class="table table-bordered"></p>
    <div class="from-row field-no">
        <div >
            <label class="required" for="id_no">
                学号：
            </label>
            <input type="number" name="no" class="vIntegerField" required id="id_no" value="{{ next_no }}">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-name">
        <div>
            <label class="required" for="id_name">
                姓名:
            </label>
            <input type="text" name="name" class="vTextField" maxlength="20" required id="id_name">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-age">
        <div>
            <label class="required" for="id_age" >
                年龄：
            </label>
            <input type="number" name="age" class="vIntegerField" min="0" required id="id_age">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-gender">
        <div>
            <label class="required" for="id_gender">
                性别：
            </label>
            <select name="gender" id="id_gender">
                <option value="0" selected>未选择</option>
                <option value="1" >男</option>
                <option value="2" >女</option>
                <option value="3" >保密</option>
            </select>
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-phone">
        <div>
            <label for="id_phone">
                电话号码：
            </label>
            <input type="text" name="phone" class="vTextField" maxlength="50" id="id_phone">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-avatar">
        <div>
            <label class="required" for="id_avatar">
                头像
            </label>
            <input type="file" name="avatar" accept="image/*" required id="id_avatar">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="submit-row">
        <input type="submit" value="提交" class="default" name="_save">
    </div>
</form>
</body>
</html>

templates/student/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除学生信息</title>
</head>
<body>
<h1>删除成功</h1>
<a href="/student/index"><button>返回首页</button></a>
</body>
</html>

templates/student/do_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改成功</title>
</head>
<body><h1>修改成功</h1>
<a href="/student/index"><button>返回首页</button></a></body>
</html>

templates/student/export_excel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>导出excel</title>
</head>
<body>

</body>
</html>

templates/student/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生管理系统-首页</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e7448b18a1.js"></script>

    {% load static %}
</head>
<body>
<div class="container">
    <h1 class="info">学生列表</h1>
    <p class="table table-bordered"></p>

    <a href="/student/add"><button class="btn btn-warning btn-lg float-right">添加一个学生信息<i class="fas fa-plus"></i></button></a>
    <a href="/student/export_excel"><button type="button" class="btn btn-warning btn-lg">导出excel学生列表</button></a>
    <a href="/student/select/"><button type="button" class="btn btn-warning btn-lg float-center">查询学生信息</button></a>

    <table class="table">
        <tr class="thead-dark">
            <th>#</th>
            <th>学号</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>电话</th>
            <th>头像</th>
            <th>加入时间</th>
            <th>操作</th>
        </tr>
         {% for a in student_list %}
        <tr>
            <td><input type="checkbox" name="student"></td>
            <td>{{a.no }}</td>
            <td>{{ a.name }}</td>
            <td>{{ a.age }}</td>
            <td>{{ a.get_gender_display }}</td>
            <td>{{ a.phone }}</td>
            <td><img src="/media/{{ a.avatar }}" width="50px" height="50px"></td>
            <td>{{ a.join_time | date:"Y-m-d H:i:s"}}</td>
            <td><a href="/student/{{ a.id}}/update">修改<i class="fas fa-edit"></i></a>&nbsp;&nbsp; <a href="/student/{{ a.id}}/delete">删除<i class="fas fa-trash"></i></a></td>
        </tr>
        {% endfor %}
    </table>
<!--分页-->
    <nav aria-label="page navigation">
        <ul class="pagination">
             <li class="page-item">
                 <a class="page-link" href="?page_no={{ page_previous }}&page_size=3">上一页</a></li>
            {% for i in page_amount_list%}
                <li {% if forloop.counter == page_nex%}
                     class="page-item active"
                    {% else %}
                    class="page-item"
                    {% endif %}
                >
                    <a  href="/student/index/?page_no={{ forloop.counter }}&page_size=3" class="page-link">{{ forloop.counter }}</a>
                </li>
            {% endfor %}
            <li class="page-item"><a class="page-link" href="?page_no={{ page_nex }}&page_size=3">下一页</a></li>
        </ul>
    </nav>
</div>

</body>
</html>

templates/student/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询学生信息</title>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
     <script src="https://kit.fontawesome.com/e7448b18a1.js"></script>
    <style>
        body{
            margin-top: 100px;
        }
    </style>
</head>
<body class="container">
<form method="post" action="/student/select/">
    {% csrf_token %}
    <strong>关键字</strong><input type="text" name="name">
    <STRONG>性别</STRONG><input type="text" name="gender">
    <input type="submit" value="查询">

</form>
    <table class="table">
        <tr class="thead-dark">
            <th>#</th>
            <th>学号</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>电话</th>
            <th>头像</th>
            <th>加入时间</th>
            <th>操作</th>
        </tr>
         {% for a in student_list %}
        <tr>
            <td><input type="checkbox" name="student"></td>
            <td>{{a.no }}</td>
            <td>{{ a.name }}</td>
            <td>{{ a.age }}</td>
            <td>{{ a.get_gender_display }}</td>
            <td>{{ a.phone }}</td>
            <td><img src="/media/{{ a.avatar }}" width="50px" height="50px"></td>
            <td>{{ a.join_time | date:"Y-m-d H:i:s"}}</td>
            <td><a href="/student/{{ a.id}}/update">修改<i class="fas fa-edit"></i></a>&nbsp;&nbsp; <a href="/student/{{ a.id}}/delete">删除<i class="fas fa-trash"></i></a></td>
        </tr>
        {% endfor %}
    </table>
  <a href="/student/index/"><button class="btn btn-warning btn-lg float-right">返回首页</button></a>
</body>
</html>

templates/student/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生列表</title>
</head>
<body>
 <table class="table">
        <tr class="thead-dark">
            <th>#</th>
            <th>学号</th>
            <th>姓名</th>
            <th>年龄</th>
            <th>性别</th>
            <th>电话</th>
            <th>头像</th>
            <th>加入时间</th>
            <th>操作</th>
        </tr>
     <tr>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
     </tr>
 </table>
<SCRIPT>

</SCRIPT>
</body>
</html>

templates/student/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加成功</title>
</head>
<body>
<h1>添加成功</h1>
<a href="/student/add"><button>继续添加</button></a>
<a href="/student/index"><button>返回首页</button></a>
</body>
</html>

templates/student/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改学生信息</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="https://kit.fontawesome.com/c269860567.js"></script>
    <style>
        div{
            text-align: center;
        }
    </style>
</head>
<body>

<form enctype="multipart/form-data" action="/student/{{ students.id }}/do_update/" method="post" id="student_from" novalidate>
    {% csrf_token %}
    <h1 align="center">修改student</h1>
    <p class="table table-bordered"></p>
    {% for id in stu %}
    <div class="from-row field-no">
        <div >
            <label class="required" for="id_no">
                学号：
            </label>
            <input type="number" name="no" class="vIntegerField" required id="id_no" value="{{ id.no }}">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-name">
        <div>
            <label class="required" for="id_name">
                姓名:
            </label>
            <input type="text" name="name" class="vTextField" maxlength="20" required id="id_name" value="{{ id.name}}">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-age">
        <div>
            <label class="required" for="id_age" >
                年龄：
            </label>
            <input type="number" name="age" class="vIntegerField" min="0" required id="id_age" value="{{ id.age }}">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-gender">
        <div>
            <label class="required" for="id_gender">
                性别：
            </label>
            <select name="gender" id="id_gender">
                <option value="{{id.gender  }}" selected="">{{ id.get_gender_display }}</option>
                <option value="0" >未选择</option>
                <option value="1" >男</option>
                <option value="2" >女</option>
                <option value="3" >保密</option>
            </select>
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-phone">
        <div>
            <label for="id_phone">
                电话号码：
            </label>
            <input type="text" name="phone" class="vTextField" maxlength="50" id="id_phone" value="{{id.phone  }}">
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="from-row field-avatar">

        <div>
            <p> 当前：<a href="{{ id.avatar  }}">{{ id.avatar }}</a>
            <label class="required" for="id_avatar">
                头像
            </label>

            <input type="file" name="avatar" accept="image/*" required id="id_avatar" > </p>
        </div>
    </div>
    <p class="table table-bordered"></p>
    <div class="submit-row">
        <input type="submit" value="提交" class="default" name="_save">
    </div>
    {% endfor %}
</form>
</body>
</html>